name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies1
        run: npm install
      - run: npm run build --if-present
      - name: Commit package-lock.json
        run: |
          git config --global user.name 'Mark Renovate'
          git config --global user.email 'mjmarryatt@gmail.com'
          git add package-lock.json
          git commit -m "package-lock automated update"
          git push origin ${GITHUB_REF##*/}
