name: Node.js CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '#noci') }}
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies and update package-lock.json
        run: npm install
      - run: npm run build --if-present
      - name: Commit package-lock.json
        id: commit
        continue-on-error: true
        run: |
          git config --global user.name 'Mark Renovate'
          git config --global user.email 'mjmarryatt@gmail.com'
          git status
          git add package-lock.json
          git commit -m "#noci package-lock automated update"
          git push origin ${{ github.event.pull_request.head.ref }}
      - name: debug
        run: echo ${{ steps.commit.outputs.stdout }}
